version: '3.8'
services:
  validation-service:
    build: ./validation-service
    container_name: validation-app
    ports:
      - "8081:8081"
    networks:
      - banque-net

  transaction-service:
    build: ./transaction-service
    container_name: transaction-app
    ports:
      - "8082:8082"
    networks:
      - banque-net
    depends_on:
      - validation-service

networks:
  banque-net:
    driver: bridge