apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
        - name: transaction-service
          image: docker.io/library/transaction-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: VALIDATION_SERVICE_URL
              value: "http://validation-service:8081"
