apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082 # Port fixe pour tester sur ton navigateur
  type: NodePort
