apiVersion: v1
kind: Service
metadata:
  name: validation-app # C'est le nom DNS que le service Transaction utilisera
spec:
  selector:
    app: validation # Il cible les pods avec ce label
  ports:
    - protocol: TCP
      port: 8081 # Port exposé par le service
      targetPort: 8081 # Port sur lequel l'application écoute dans le pod
  type: ClusterIP # Type par défaut : accessible uniquement à l'intérieur du cluster
